CREATE DATABASE tp_db_homework;
CREATE USER korolion WITH ENCRYPTED PASSWORD 'qwerty123';
GRANT ALL PRIVILEGES ON DATABASE tp_db_homework TO korolion;
\c tp_db_homework
CREATE EXTENSION IF NOT EXISTS CITEXT;
